;;; tests.el --- emacs-dsh tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'emacs-dsh)

(ert-deftest emacs-dsh-compose-and-history ()
  (with-temp-buffer
    (emacs-dsh-chat-mode)
    (setq-local emacs-dsh--root "/tmp/" emacs-dsh--session-id "s1")
    (emacs-dsh--compose)
    (should (emacs-dsh--input-widget))
    (emacs-dsh--replace-draft "hello")
    (should (equal (emacs-dsh--draft-text) "hello"))
    (emacs-dsh--event '((type . "user/message") (seq . 0)
                        (data . ((role . "user") (content . (((type . "text") (text . "hello"))))))))
    (should (equal emacs-dsh--last-prompt "hello"))
    (should (string-match-p "You: hello" (buffer-string)))
    (should (equal (emacs-dsh--draft-text) "hello"))))

(ert-deftest emacs-dsh-wire-shapes ()
  (let* ((payload '((request . ((requestId . "r1")
                                 (sessionId . "s1") (mode . "queue")
                                 (content . [((type . "text") (text . "hi"))])))))
         (decoded (json-parse-string (json-serialize payload)
                                     :object-type 'alist :array-type 'array))
         (content (alist-get 'content (alist-get 'request decoded))))
    (should (equal (alist-get 'text (aref content 0)) "hi"))))

(ert-deftest emacs-dsh-stream-and-replay ()
  (with-temp-buffer
    (emacs-dsh-chat-mode)
    (setq-local emacs-dsh--root "/tmp/" emacs-dsh--session-id "s1")
    (emacs-dsh--compose)
    (emacs-dsh--stream '((type . "start") (attemptId . "a1")))
    (emacs-dsh--stream '((type . "chunk") (attemptId . "a1")
                         (chunk . ((type . "text-delta") (text . "hello")))))
    (should (string-match-p "hello" (overlay-get emacs-dsh--stream-overlay 'before-string)))
    (let ((event `((type . "assistant/message") (seq . 2)
                   (data . ((message . ((content . ,(list '((type . "text") (text . "hello")))))))))))
      (emacs-dsh--event event)
      (should-not (overlay-get emacs-dsh--stream-overlay 'before-string))
      (emacs-dsh--event event)
      (should (= 1 (cl-count-if (lambda (line) (string-prefix-p "DSH: hello" line))
                                (split-string (buffer-string) "\n")))))))

(ert-deftest emacs-dsh-paths ()
  (should (equal (emacs-dsh--file-ref "/tmp/foo bar.txt" "/tmp/") "@\"foo bar.txt\""))
  (should (equal (emacs-dsh--file-ref "/tmp/a.txt" "/tmp/") "@a.txt")))
